### ISSUE TITLE
добавить spell checker и другие прибаутки для проверки текста 

### ISSUE THREAD

**Issue by vtrokhymenko** [SemyonSinchenko/qmlcourse#104]
для примера можно посмотреть как это сделали товарищи с https://github.com/tlbootcamp/tlroadmap
* https://github.com/tlbootcamp/tlroadmap/blob/master/.github/workflows/tlroadmap_workflow.yaml

**Comment by dkorzhov** [comment]
@vtrokhymenko Привет. Можешь сделать новый branch? У меня нет прав на создание. Закину туду PR по spell checker.

**Comment by SemyonSinchenko** [comment]
@dkorzhov Прими акцепт, будут права. Так проще будет. Сейчас ты висишь в ожидании:
![image](https://user-images.githubusercontent.com/29755009/127734621-412d8b04-a0f9-4c81-b845-ef8980a305df.png)

Поищи в почте, должно было быть письмо с приглашением.

**Comment by dkorzhov** [comment]
Нашел только старое письмо. Пишет что там акцепт истек. Можешь перевыслать?

**Comment by SemyonSinchenko** [comment]
> Нашел только старое письмо. Пишет что там акцепт истек. Можешь перевыслать?

Отправил!

**Comment by dkorzhov** [comment]
Спасибо. Отправил #118

**Comment by vtrokhymenko** [comment]
@dkorzhov спасибо за помощь, как всегда выручил. только давай след раз не fork делать, а сразу новую ветку и pr внутри этого репо
