### ISSUE TITLE
Лекция про Hardware

### ISSUE THREAD

**Issue by SemyonSinchenko** [SemyonSinchenko/qmlcourse#11]
NISQ и все вот это. Основной посыл - люди должны понять, почему у нас всякие вариационные эвристики, а не HHL.

**Comment by karelin** [comment]
Нашел копию книги 2016 года, по ссылке на свою работу ;) , в том числе с разделом по Silicon Quantum Photonics
http://ndl.ethernet.edu.et/bitstream/123456789/75674/1/305.pdf#page=63

Может быть, кому-то поможет для написания текста по Hardware
