### ISSUE TITLE
убедиться что в `contributing.md` все понятно описано и последовательность действий правильная

### ISSUE THREAD

**Issue by vtrokhymenko** [SemyonSinchenko/qmlcourse#111]

**Comment by SemyonSinchenko** [comment]
Там если некорректное форматирование (пробелы в конце строк), то pre-commit падает с status 1. Кажется очень не информативно. Надо как-то писать трабл-шутинг для таких случаев (типа запустите встроенный в ваш редактор форматтер кода, я могу для emacs написать, но наверное надо добавить и для VSCode/Atom/Sublime и что там еще популярно). Потому что нифига не понятно что делать и как вообще понять в какой строке проблема.

**Comment by vtrokhymenko** [comment]
если выполнить правильно https://github.com/SemyonSinchenko/qmlcourse/blob/master/CONTRIBUTING.md#run-pre-commit-hooks-before-building, то pre-commit все изменит, нужно после того залить в gh

**Comment by SemyonSinchenko** [comment]
Все понял, моя ошибка. Не внимательно читал)

**Comment by SemyonSinchenko** [comment]
Кстати предварительный запуск по инструкции тоже не особо информативно ругается
![image](https://user-images.githubusercontent.com/29755009/127492136-3893cbb5-3b1a-47c7-8de5-af0930f19241.png)

**Comment by vtrokhymenko** [comment]
возможно, не буду спорить. видимо привык
в твоем снимке он пишет что и где упало, но если сделать `git diff`, то сразу увидишь что у чему
