### ISSUE TITLE
Решить вопрос с установкой psi4

### ISSUE THREAD

**Issue by SemyonSinchenko** [SemyonSinchenko/qmlcourse#113]
В лекции по квантовой химии в примерах испольузется либа psi4. У нее очень специфичный способ установки.

Хочется:
- Создать makefile
- Вынести установку всех зависимостей в make install (потому что вместе с установкой psi4 это будет уже целый скрипт)
- Вынести сборку книги в make build
- В CI/CD выпилить длинные команды и заменить на make

**Comment by mmm0171** [comment]
0xc4bef2ebdb7c7f72beb34db9950dcd16fef4d98f

**Comment by dkorzhov** [comment]
могу на выходных заняться

**Comment by SemyonSinchenko** [comment]
> могу на выходных заняться

Это был бы очень крутой вклад! @zimka также может помочь консультацией по сборке этого пакета.

**Comment by zimka** [comment]
Было бы очень очень здорово!
Мои наблюдения пока по установке ps4 такие:
- Т.к. psi4 включает в себя кучу qc пакетов на плюсах, её основной способ установки -- через conda, на [странице загрузки](https://psicode.org/installs/v14rc3/) все варианты подразумевают установку cond-ы, и через нее все в одну строчку действительно. На Pypi пакета просто нет.
- Если не через конду, то надо билдить через CMake, самому все хедеры/либы устанавливать для сборки, тут вот есть  [инструкция](https://psicode.org/psi4manual/master/build_planning.html#faq-cmakeviasetup)
- В репозитории есть azure [пайплайн](https://github.com/psi4/psi4/blob/master/.azure-pipelines/azure-pipelines-linux.yml), с помощью которого conda пакет собирают, возможно, его можно как-то включить с минимальными изменениями в CI
- Есть ubuntu deb [psi4](https://pkgs.org/download/psi4), я его установливал, но он похоже не включает в себя Python биндинги
- У меня был хитрый план, до которого не дошли руки: попробовать сделать conda env с psi4, и пробросить пакет из conda env в venv/poetry через символьную ссылку. Я не работал раньше с poetry, но такой трюк с **ln -s** чтобы пробросить системно установленные python-либы в конкретный venv использовал и все работало.

**Comment by SemyonSinchenko** [comment]
Я даже допускаю, что можно установить внутрь poetry-окружения через conda. Главное чтобы вся магия была в make, а для пользователя это было бы одной командой. Ну либо вариант со сборкой из исходников.

**Comment by SemyonSinchenko** [comment]
У нас еще и проблемы с виндой. Там ряд пакетов не доступен. Надо попробовать сделать make-file так, чтобы он для разных ОС работал по разному

**Comment by vtrokhymenko** [comment]
есть ещё docker, но вопрос нужно ли его тащить сюда. или просто забить на win

**Comment by SemyonSinchenko** [comment]
> есть ещё docker, но вопрос нужно ли его тащить сюда. или просто забить на win

Docker на винде это также больно(
Забивать не хочется, потому что сейчас конфликты лишь в tfq и psi4, а без них курс вполне можно пройти. Все остальное должно ставится. Поэтому и хочется разные make-файлы, или разные инструкции там...

**Comment by dkorzhov** [comment]
Предлагаю по порядку разобрать задачи)
Как я понял, нам надо:
1. Использовать psi4 в CI на Linux.
2. Использовать psi4 в CI на Windows.
3. Добавить makefile, чтобы можно было скачать курс и поставить все необходимое на Linux.
4. Добавить makefile, чтобы можно было скачать курс и поставить все необходимое на Windows.
5. Сделать запуск из CI makefile, чтобы не было расхождений в двух местах.
Верно понял?

**Comment by SemyonSinchenko** [comment]
@dkorzhov Да!

**Comment by vtrokhymenko** [comment]
> Предлагаю по порядку разобрать задачи)
> Как я понял, нам надо:
> 
> 1. Использовать psi4 в CI на Linux.
> 2. Использовать psi4 в CI на Windows.
> 3. Добавить makefile, чтобы можно было скачать курс и поставить все необходимое на Linux.
> 4. Добавить makefile, чтобы можно было скачать курс и поставить все необходимое на Windows.
> 5. Сделать запуск из CI makefile, чтобы не было расхождений в двух местах.
>    Верно понял?

норм план, но если такая пянка, то давайте и на macos проверять, благо такое можем сделать на gh-actions

**Comment by dkorzhov** [comment]
п.1 я протестировал установку miniconda и psi4 через github actions. psi4 --test прошел вроде нормально.
https://github.com/dkorzhov/qmlcourse/runs/3208502363?check_suite_focus=true
подойдет такое решение?
п.2 в принципе мы можем добавить ноду с windows
Вот тест psi4 https://github.com/dkorzhov/qmlcourse/runs/3208646969?check_suite_focus=true

**Comment by vtrokhymenko** [comment]
> п.1 я протестировал установку miniconda и psi4 через github actions. psi4 --test прошел вроде нормально.
> https://github.com/dkorzhov/qmlcourse/runs/3208502363?check_suite_focus=true
> подойдет такое решение?
> п.2 в принципе мы можем добавить ноду с windows
> Вот тест psi4 https://github.com/dkorzhov/qmlcourse/runs/3208646969?check_suite_focus=true

вроде то что нужно. предлагаю всегда гнать тесты на всех 3х платформах с установкой зависимостей (poetry) для проверки. делается не сложно, но в то же время полезно

**Comment by dkorzhov** [comment]
#118 Добавил в PR тест для трех платформ, сейчас падает на Windows
Unable to find installation candidates for tensorflow-quantum

**Comment by vtrokhymenko** [comment]
> #118 Добавил в PR тест для трех платформ, сейчас падает на Windows
> Unable to find installation candidates for tensorflow-quantum

для этого хорошо бы иметь отдельный pr

**Comment by SemyonSinchenko** [comment]
tfq надо исключать из сборки для win. Он идет для одной факультативной лекции и это терпимо.

**Comment by dkorzhov** [comment]
> > #118 Добавил в PR тест для трех платформ, сейчас падает на Windows
> > Unable to find installation candidates for tensorflow-quantum
> 
> для этого хорошо бы иметь отдельный pr

для makefile сделаю тогда отдельный

**Comment by dkorzhov** [comment]
> tfq надо исключать из сборки для win. Он идет для одной факультативной лекции и это терпимо.

Из сборки win исключил, теперь норм.

**Comment by vtrokhymenko** [comment]
все же советуют все что связано с `test-psi4-*` сделать отдельным от spell check pr, как минимум из-за того, что это отдельная задача, а то опять кашу делаем

**Comment by vtrokhymenko** [comment]
> > tfq надо исключать из сборки для win. Он идет для одной факультативной лекции и это терпимо.
> 
> Из сборки win исключил, теперь норм.

что-то не вижу или забыл сделать commit

**Comment by dkorzhov** [comment]
> все же советуют все что связано с `test-psi4-*` сделать отдельным от spell check pr, как минимум из-за того, что это отдельная задача, а то опять кашу делаем

#120

**Comment by SemyonSinchenko** [comment]
Все же это не решение на 100%, а лишь его часть. Так как во время сборки книги psi4 будет невидим для poetry. Так что переоткрываю. Надо чтобы работало:
```
poetry run psi4 --test
```
Так как книга будет собираться именно из окружения poetry.

**Comment by dkorzhov** [comment]
Не получилось быстро решить вопрос. Попробовал разные варианты и пока остается вариант, как писал zimka с ln -s. Буду пробовать этот вариант.
Для CI надо psi4 запускать из окружения poetry, обычный вариант никак не подходит?

**Comment by SemyonSinchenko** [comment]
> Для CI надо psi4 запускать из окружения poetry, обычный вариант никак не подходит?

В теории перед запуском poetry прописать переменную PYTHONPATH добавив туда также psi4. В общем важно, чтобы эта штука была доступна в момент сборки из окружения poetry. Кмк, переменная PYTHONPATH выглядит лучше, чем ln -s

Еще есть вот такая классная штука:
https://python-poetry.org/docs/pyproject/#packages

Кажется это прямо то, что нужно - лишь захардкодить путь и все

**Comment by dkorzhov** [comment]
> > Для CI надо psi4 запускать из окружения poetry, обычный вариант никак не подходит?
> 
> В теории перед запуском poetry прописать переменную PYTHONPATH добавив туда также psi4. В общем важно, чтобы эта штука была доступна в момент сборки из окружения poetry. Кмк, переменная PYTHONPATH выглядит лучше, чем ln -s
> 
> Еще есть вот такая классная штука:
> https://python-poetry.org/docs/pyproject/#packages
> 
> Кажется это прямо то, что нужно - лишь захардкодить путь и все: мы просто указываем conda, чтобы он ставил зависимости в папку внутри корня репозитория и просто добавляем в poetry что-то типа conda/envs/**/*. Ну то есть надо все это попробовать еще конечно...

Ага, видел и тоже хотел попробовать этот вариант. Может сработает.
Но я пробовал делать нечто похожее, через poetry virtualenvs.path = "{cache-dir}/virtualenvs", но не сработало.

**Comment by SemyonSinchenko** [comment]
Тогда остаются варианты с:
- PYTHONPATH append
- ln -s
В теории можно полностью переключить сборку на conda, хотя надо будет половину мануалов переделать...

**Comment by dkorzhov** [comment]
Я еще поэксперементирую на этой неделе и по итогам примем решение.

**Comment by vtrokhymenko** [comment]
> tfq надо исключать из сборки для win. Он идет для одной факультативной лекции и это терпимо.

**Comment by dkorzhov** [comment]
по makefile задача актуальна?

**Comment by vtrokhymenko** [comment]
> по makefile задача актуальна?

пожалуй что да

**Comment by dkorzhov** [comment]
ок, сегодня-завтра займусь

**Comment by dkorzhov** [comment]
Не против, переоткрую issues.
Вопрос.
Какой способ установки  выбрать для windows? Makefile? Тогда надо выбрать какой интерпретатор выбрать и как его устаналивать. Использовать Chocolaty или нет? Или просто описать в powershell скрипте?
Будут предложения, пожелания к способу установки?

**Comment by vtrokhymenko** [comment]
> Не против, переоткрую issues.
> Вопрос.
> Какой способ установки выбрать для windows? Makefile? Тогда надо выбрать какой интерпретатор выбрать и как его устаналивать. Использовать Chocolaty или нет? Или просто описать в powershell скрипте?
> Будут предложения, пожелания к способу установки?

с win не работаю, но почему-то makefile больше всего нрав

**Comment by dkorzhov** [comment]
Закинул PR #135 Makefile для linux и macos
Много было ньюансов при тестировании, заняло время. Мака нет, поэтому проверял на github action.
Рекомендую еще потестировать на компах. Решение не идеальное, но должно работать.

Требования перед запуском:
Ubuntu:
1. Обновить: apt-get update
2. Установить sudo: apt-get install sudo -y
3. Установить make: apt-get install build-essential -y
4. Установить git: apt-get install git wget -y
5. make install-ubuntu-latest && make build

MacOS:
1. Установить brew
2. make install-macOS-latest && make build
