### ISSUE TITLE
Инструкции к spell checker-у

### ISSUE THREAD

**Issue by Yorko** [SemyonSinchenko/qmlcourse#131]
Как-то рано закрыли #126 – тесты падают из-за спелчекера, инструкций никаких нет, как этим чекером пользоваться.

@dkorzhov добавь плз инструкции, как пользоваться спелчекером, в Contributing.md. И как его бы прогнать и пофиксить опечатки. По-моему, не дело, что тесты не проходят только из-за того, что спелчекер не знает какой-то жаргонизм.

**Comment by dkorzhov** [comment]
ок, я подготовлю инструкцию

**Comment by dkorzhov** [comment]
добавил, PR #136
