### ISSUE TITLE
Убрать логи tensorflow из книги

### ISSUE THREAD

**Issue by SemyonSinchenko** [SemyonSinchenko/qmlcourse#143]
Наверное выставить TF_CPP_MIN_LOG_LEVEL  = 3 (но это не точно)
Сейчас, например, в Гровере (#142) есть такое:
![image](https://user-images.githubusercontent.com/29755009/131080878-92a268a5-07a0-402c-99fd-f8fe991cf989.png)

Куда-то в билд добавить, например.

**Comment by dkorzhov** [comment]
Добавил переменную TF_CPP_MIN_LOG_LEVEL в env build процесса.
Но из-за кэша она может не сработать, поэтому добавил при ручном запуске переменную для игнорирования кэша.
Disable cache надо запустить с параметром true, тогда кэш книги будет проигнорирован и книга соберется заново и логи TF должны уйти.
Действия возможны только после merge в master.
