### ISSUE TITLE
Лекция по superdense coding

### ISSUE THREAD

**Issue by polyzer** [SemyonSinchenko/qmlcourse#158]
Сверхплотное кодирование - важная тема, даже базовая. Обязательно надо осветить и рассказать.
https://ru.wikipedia.org/wiki/Квантовое_сверхплотное_кодирование

**Comment by dmburd** [comment]
Я займусь.

**Comment by SemyonSinchenko** [comment]
@dmburd Спасибо, это будет очень круто!
Я добавил тебя в репозиторий. Единственная просьба - делать PR из ветки, а не из форка, так как мы не настоящие девопсы и наш CI/CD по сборке staging-версии получилось настроить лишь для веток.

**Comment by dmburd** [comment]
Признаться, я новичок в совместной разработке на github. Что именно означает "делать PR из ветки, а не из форка"?
Читаю инструкцию https://isqua.ru/blog/2017/04/12/kak-otkryt-pull-riekviest-v-github-i-nie-oblazhatsia/
Там пишут "пулл-реквест должен быть из вашего форка и ветки, в которой вы делали работу". Этой инструкции можно следовать точно? Или нужно что-то сделать по-другому?

**Comment by SemyonSinchenko** [comment]
Не, у нас используются SSH токены и Git Actions, поэтому у нас надо сделать ветку именно в этом репозитории. Что-то типа:
```
git checkout -b lecture/super_dense_coding
git add ...
git commit ...
```

И работать в ветке. А потом именно из нее открывать PR.

**Comment by dmburd** [comment]
После git commit сделать
git push --set-upstream origin lecture/super_dense_coding
верно?

**Comment by SemyonSinchenko** [comment]
Ага. Ну или просто сделать `git push origin lecture/super_dense_coding`
