### ISSUE TITLE
Добавить сборку PDF

### ISSUE THREAD

**Issue by SemyonSinchenko** [SemyonSinchenko/qmlcourse#163]
@dkorzhov Сможешь посмотреть?
Дело в том, что на ODS.ai надо будет грузить PDF (так вышло). Наверное, надо какую-то подпапку создать для PDF-к. Ну и в целом проверить, что оно реально работает.

Наверное, отправная точка тут: https://jupyterbook.org/advanced/pdf.html
Там два варианта, я на самом деле не пробовал.

**Comment by dkorzhov** [comment]
ок, начну сегодня разбираться

**Comment by dkorzhov** [comment]
Закинул PR #165 
Пока сделал так:
Добавил новый шаг в основной pipeline pre-commit-deploy-book, но поставил запуск конвертации в pdf только при ручном запуске, чтобы на PR время не терялось. 
После билда книга находится в ветке gh-pages: qmlcourse/_build/pdf/book.pdf

P.S. я там случайно обновил напрямую в master два файла: poetry.lock, pyproject.toml. Прошу прощение)
