### ISSUE TITLE
Сломалась страница в GH-pages

### ISSUE THREAD

**Issue by SemyonSinchenko** [SemyonSinchenko/qmlcourse#168]
Сейчас там вот так:
![image](https://user-images.githubusercontent.com/29755009/133921464-9c4e9d65-6541-4969-8e60-d979c4bb8911.png)
А на этой странице должна быть именно книга.

Вероятно причина в тестах в связи с #165, но суть в том, что так не должно быть. Вероятно, необходимо, чтобы оно билдилось в разные папки, либо шаг с главным билдом книги был последний. Довольно критичный момент короче...

**Comment by dkorzhov** [comment]
перезапустил с мастера, все исправилось.
может вынести формирование pdf в отдельный pipeline, запускать его вручную по необходимости и он будет только формировать артефакты без деплоя в gh-pages?

**Comment by SemyonSinchenko** [comment]
А можно деплоить, но вне пути, который отображается в браузере? Чтобы в ветке ghpages был какой-то "скрытый" путь или что-то такое?

**Comment by dkorzhov** [comment]
Пока не удалось скрыть pdf в ветке gh-pages так как добавлена настройка nojekyll.
Буду еще искать инфо.

**Comment by dkorzhov** [comment]
Раз решили оставить pdf в публичном доступе, думаю этот issues можно закрыть.
