### ISSUE TITLE
Лекция про основы Python

### ISSUE THREAD

**Issue by Yorko** [SemyonSinchenko/qmlcourse#17]
Ликбез про Python + как развернуть среду. Ничего сложного, ЦА – люди, вообще не знакомые с питоном. 
Детального плана мы тут не делали. Лекция пойдет сюда в репу и на сайт [qmlcourse.ai](qmlcourse.ai), но конечно, не на хабр.

Формат – JupyterBook (markdown). 

---
- [x] python_lec_1: Вводная лекция про Python
- [x] #172
- [x] python_lec_3: Ориентация в Jupyter
- [x] python_lec_4: Переменные, типы и вывод
- [x] python_lec_5: Условия и сравнения
- [x] python_lec_6: Списки и циклы
- [x] #173
- [x] #174
- [x] python_lec_10: Объекты и классы
- [x] python_lec_11: Финальная лекция
----
- [x] #175

**Comment by stalkermustang** [comment]
Начал работу в #70 , там вкратце рассказывается про питон (на 10-30 минут)
Соответствует пункту 1 плана:
>Вводное занятие про питон.

Пункт 2 (про установку poetry + jupyter) пока пропустил. 
Пункт 3 "Ориентация в Jupyter + интерфейс" почти доделал, сейчас немного переверстываю + переношу в MD.

Дайте, пожалуйста, фидбек по первой пробной части, по стилю написания, обрамлению, etc, чтобы я понимал, в каком формате давать материал. Ориентировочно к среде выложу 3й блок.

**Comment by SemyonSinchenko** [comment]
@stalkermustang Мне оч нравится! Приятно и легко читать, стиль :+1:

**Comment by Yorko** [comment]
Годно! Я в самом PR #70 дал фидбек

**Comment by stalkermustang** [comment]
Пажите а почему Issue закрыто?

**Comment by SemyonSinchenko** [comment]
> Пажите а почему Issue закрыто? 

PR смержили оно и закрылось

**Comment by vtrokhymenko** [comment]
про `while` собираетесь рассказывать?

**Comment by stalkermustang** [comment]
> про `while` собираетесь рассказывать?

![image](https://user-images.githubusercontent.com/26546178/128051112-ca3ab2f6-e6c2-4f97-bb0a-7fdc4112ce73.png)
включено в план

**Comment by vtrokhymenko** [comment]
> > про `while` собираетесь рассказывать?
> 
> ![image](https://user-images.githubusercontent.com/26546178/128051112-ca3ab2f6-e6c2-4f97-bb0a-7fdc4112ce73.png)
> включено в план

спс, план скрытый, вот и прошляпил

**Comment by stalkermustang** [comment]
@vtrokhymenko как то можно сделать чтобы оно не закрывало его каждый раз с новым  MR? при том что вообще то висит еще один открытый (по 6й лекции), и правила переноса не должны срабатывать

**Comment by vtrokhymenko** [comment]
> @vtrokhymenko как то можно сделать чтобы оно не закрывало его каждый раз с новым MR? при том что вообще то висит еще один открытый (по 6й лекции), и правила переноса не должны срабатывать

можно, но для этого нужно создать родительский issue, где прописать отдельные дочерние (вот [видео](https://www.youtube.com/watch?v=BplF7vHXewA) для примера)

**Comment by vtrokhymenko** [comment]
- [ ] lec_1: Вводная лекция про Python
- [ ] lec_2: Установка инструментов
- [ ] lec_3: Ориентация в Jupyter
- [ ] lec_4: Переменные, типы и вывод
- [ ] lec_5: Условия и сравнения
- [ ] lec_6: Списки и циклы
- [ ] lec_7: Словари
- [ ] lec_8: <не_нашел_pr>
- [ ] lec_9: <не_нашел_pr>
- [ ] lec_10: Объекты и классы
- [ ] lec_11: Финальная лекция
