### ISSUE TITLE
устранить рендер формул в pdf книге

### ISSUE THREAD

**Issue by vtrokhymenko** [SemyonSinchenko/qmlcourse#198]
в курсе полно всяких формул и при скачивании книги получается вот такое, негоже
<img width="738" alt="image" src="https://user-images.githubusercontent.com/8581044/137591964-968a82c1-a91d-4571-87ac-f7b7aa5a37eb.png">

**Comment by vtrokhymenko** [comment]
@dkorzhov есть идеи как можно решить эту проблему?

**Comment by dkorzhov** [comment]
> @dkorzhov есть идеи как можно решить эту проблему?

@vtrokhymenko 
Попробовал несколько идей, пока не сработало.
Сейчас мы используем builder pdfhtml для получения pdf. По описанию он должен переводить формулы, но на сайте он стоит как эксперементальный и могут быть баги.

Пробовал разные варианты с pdflatex и просто получить tex файл, но все эти варианты падают на svg файле вот с такой ошибкой:
subprocess.CalledProcessError: Command '['convert', './qmlcourseRU/_static/qcblock/gates/CNOT_gate.svg[0]', ./qmlcourseRU/_build/.doctrees/images/CNOT_gate.png']' returned non-zero exit status 1.

Пока не понятно, может он с svg вообще не работает. Но ставил разные доп.пакеты, пробовал на последней версии jupyter-book, на разных python - все равно падает. Пишут, что косяк может быть в svg файлах. Менял svg на другой, все равно ругается, возможно на всех svg будет ругаться.

**Comment by alexey-pronkin** [comment]
Займусь этой проблемой, как лучше сделать - накатить патч на установленный пакет или форкнуть jupyter book, исправить в исходниках и установить из гита?

**Comment by vtrokhymenko** [comment]
> Займусь этой проблемой, как лучше сделать - накатить патч на установленный пакет или форкнуть jupyter book, исправить в исходниках и установить из гита?

мне больше пока нрав идея с patch

**Comment by SemyonSinchenko** [comment]
Мне вообще больше нравится идея сделать наконец сборку в latex

**Comment by vtrokhymenko** [comment]
если что, но создание pdf в комментах сейчас
https://github.com/SemyonSinchenko/qmlcourse/blob/7bc27cf5542b9bbbd1b6833dfce298037973f472/.github/workflows/deploy-book.yml#L105-L115

**Comment by SemyonSinchenko** [comment]
> если что, но создание pdf в комментах сейчас

Так и задумано.
