### ISSUE TITLE
Лекция про матрицы плотности и энтропию [срок 04.08.21, финальный срок конец августа]

### ISSUE THREAD

**Issue by SemyonSinchenko** [SemyonSinchenko/qmlcourse#2]
Люди уже будут знать, что такое состояние и оператор. Идейно я вижу лекцию про матрицы плотности побочной от основной ветки курса, то есть без домашек. Хочется, чтобы на ней осветились темы:

- Матрицы плотности
- Запутанность
- Энтропия фон Неймана как мера запутанности
- Как можно переписать то, что люди уже знают (состояния и операторы) на матрицы плотности

По времени - от 20 минут и больше. Идеально, если лекция + статья в втде текста (статьи будут идти на Хабр и в ODS).

**Comment by SemyonSinchenko** [comment]
@Bortania Ты все еще готова заниматься этой лекцией? Я что-то писал в ods тебе, но ответа нет.

**Comment by SemyonSinchenko** [comment]
@karelin @doktrster коллеги, Таня не отвечает, тогда может кто-то из вас хочет сделать эту часть?

**Comment by karelin** [comment]
Если @doktrster не возьмется в ближайшие дни, то на выходных прикину развернутый план.
Нужна заготовка лекции (презентация) или текст для главы в курс?

**Comment by SemyonSinchenko** [comment]
> Если @doktrster не возьмется в ближайшие дни, то на выходных прикину развернутый план.
> Нужна заготовка лекции (презентация) или текст для главы в курс?

Пока текст главы для курса. Это будет лекция "продвинутого" уровня, так что можно любое количества матана добавлять. Ну и потом как дойдет дело до записи видео нужно будет еще записаться.

**Comment by karelin** [comment]
> Пока текст главы для курса. Это будет лекция "продвинутого" уровня, так что можно любое количества матана добавлять. Ну и потом как дойдет дело до записи видео нужно будет еще записаться.

Я правильно понимаю, что эта глава планируется чисто дополнением к вводному материалу про кубиты и собственно QML там особо не надо?

**Comment by SemyonSinchenko** [comment]
> > Пока текст главы для курса. Это будет лекция "продвинутого" уровня, так что можно любое количества матана добавлять. Ну и потом как дойдет дело до записи видео нужно будет еще записаться.
> 
> Я правильно понимаю, что эта глава планируется чисто дополнением к вводному материалу про кубиты и собственно QML там особо не надо?

Да, это расширенный уровень. Просто тема mixed states сложная, при этом базовый QML (типа как в лекции про SVM) можно рассказать и без mixed states. Но поскольку тема оч важная и принципиальная, то хочется иметь ее в курсе, потому в реальности никто не работает с волновыми функциями, а все работают с матрицами плотности.

**Comment by karelin** [comment]
> Да, это расширенный уровень. Просто тема mixed states сложная, при этом базовый QML (типа как в лекции про SVM) можно рассказать и без mixed states. Но поскольку тема оч важная и принципиальная, то хочется иметь ее в курсе, потому в реальности никто не работает с волновыми функциями, а все работают с матрицами плотности.

Гм, а можно ссылку на хорошую статью, где "**все**" работают с матрицами плотности? Мне бы современный контекст понять, чтобы проще было структурировать текст, а то голова пока думает только про разложение Шмидта и все такое.

**Comment by SemyonSinchenko** [comment]
Гммм. Наверное я погорячился... Мне сразу в голову приходит задача томографии и во всех статьях по томографии восстанавливают матрицы плотности. Ну и от научрука слышал эту фразу, что пси функции хороши, когда мы теорему доказываем. На практике везде типа матрицы... @ooovector ты же шаришь в этом, может подскажешь, что там в реальности на практике?

**Comment by karelin** [comment]
У меня в чем проблема: я поскольку активно от темы отошел 15 лет тому как, то многие новые наработки просто не знаю (не, purity и энтропию фон Неймана никто не отменял, но контекста не хватает). Уже нашел несколько материалов на сайте PennyLane, может хватит для начала и гляну Nielsen/Chuang. А может придется пару своих статей перечитать 😺 

@SemyonSinchenko Может тогда спроси научного руководителя, что есть свежее по QML и mixed states, доступное пониманию PhD из индустрии.

**Comment by doktrster** [comment]
Я смогу подключиться к теме матрицы плотности после 20 июня, после того, как отправлю материал по алгоритмам Дойча и Гровера. Так что если будет нужно какие-то главы написать, то я готов.

**Comment by karelin** [comment]
Сделал заготовку и начальный план: https://github.com/SemyonSinchenko/qmlcourse/tree/mixedstates

**Comment by SemyonSinchenko** [comment]
> Сделал заготовку и начальный план: https://github.com/SemyonSinchenko/qmlcourse/tree/mixedstates

Выглядит супер
