### ISSUE TITLE
Разобраться со сборкой (проблемы с tfq и psi4)

### ISSUE THREAD

**Issue by SemyonSinchenko** [SemyonSinchenko/qmlcourse#207]
Проблемы с TFQ
Проблемы с Psi4

Начало обсужднения тут: https://github.com/SemyonSinchenko/qmlcourse/pull/194

**Comment by vtrokhymenko** [comment]
с tfq пока разобрались след образом, но это костыль
https://github.com/SemyonSinchenko/qmlcourse/blob/8defeab0c5e65fb13f51df2418b298481a43a463/.github/workflows/deploy-book.yml#L61-L67

**Comment by vtrokhymenko** [comment]
вопрос с psi4 всё ещё открыт
