### ISSUE TITLE
Добавить vault и D-Wave token

### ISSUE THREAD

**Issue by SemyonSinchenko** [SemyonSinchenko/qmlcourse#229]
Надо:
1. Добавить какой-то волт для переменных
2. Написать в D-Wave и выпросить токен
3. Добавить токен в волт
4. Настроить конфигурацию токена в CI/CD как тут: https://docs.ocean.dwavesys.com/en/latest/overview/sapi.html#sapi-access

Это нужно, чтобы отрабатывал код лекции по D-Wave. Учитывая, что у нас все кешируется, у нас будут обращения максимум раз в неделю, так что Free Access для Developers должно хватить. Токен для тестов в личку может скинуть @meandmytram, а потом я пообщаюсь с D-Wave и попрошу у них постоянный токен.

Я просто не знаю, как в GitHub прописываются секретные переменные для сборки. Если их должен прописать я сам, то киньте в меня названием переменной (как она будет юзаться в CI/CD) и инструкцией по тому, где тут прописывать.

Аффектит: #218 #94

**Comment by Yorko** [comment]
@meandmytram привет! Накидал [шаблон письма](https://docs.google.com/document/d/1DLAjURaZIRZZTt-QhbeejdndSgxEC_1VjiY1L0u5Ncw/edit?usp=sharing) к DWave с клянчингом токена, от нас двоих. Зацени плз.

**Comment by meandmytram** [comment]
Огонь, спасибо @Yorko! Я посмотрел и внес небольшие предложение по изменению текста, давай еще проитерируемся несколько раз и можно отправлять, мне кажется.
