### ISSUE TITLE
Лекция по квантовой химии

### ISSUE THREAD

**Issue by SemyonSinchenko** [SemyonSinchenko/qmlcourse#24]
Рассказать про задачи в целом и подходы.
Особенно важно рассказать Hatri-Fock и coupled-cluster, так как очень хочется отдельной лекцией рассказать Unitary-Coupled-Cluster anzatz для VQE.

Текстовая лекция + видео.

**Comment by zimka** [comment]
PR по self-consitent field
https://github.com/SemyonSinchenko/qmlcourse/pull/76
@SemyonSinchenko @ismorphism
