### ISSUE TITLE
Угол тета в алгоритме Гровера

### ISSUE THREAD

**Issue by 9dogs** [SemyonSinchenko/qmlcourse#276]
Читаю в лекции:
>При большом количестве итераций $t$ угол $\theta$ будет стремиться к $0$, так что его можно заменить на $\sin{\theta}$, который, в свою очередь, равен $\frac{1}{\sqrt{N}}$
([соотв. код](https://github.com/SemyonSinchenko/qmlcourse/blob/c179c2ee1360110173eaa62f0413b1ae6d5105d5/qmlcourseRU/book/qcalgo/grovers_algorithm.md?plain=1#L183))

Кажется странным, что угол θ уменьшается при увеличении числа итераций, ведь при правильном числе итераций он должен быть близок к pi/2.
Может должно быть что-то вроде:
>при большом числе кубитов $N$ начальное значение угла $\theta$ будет стремиться к $0$

?

**Comment by SemyonSinchenko** [comment]
@SergeiShirkin Посмотришь?

**Comment by SergeiShirkin** [comment]
@9dogs Угол θ- это изначальный угол между гиперплоскостью всех состояний кроме искомого и искомым состоянием (иногда его могут обозначать как θ/2). Углу pi/2 должен быть в идеале равен (2i+1)*θ, где i - общее число итераций. Для разного количества N и K необходимо разное количество итераций и разный угол θ. Чем меньше θ, тем больше нужно итераций. В тексте объясняется, как получена формула для оценки числа итераций, поэтому там говорится, что когда итераций много, угол θ близок к нулю. Имеется в виду не текущее количество итераций (сколько сделано на данный момент), а общее.

**Comment by SergeiShirkin** [comment]
"при большом числе кубитов $N$ начальное значение угла $\theta$ будет стремиться к $0$" тут общий смысл правильный, но не совсем точно, сейчас подумаю, как поправить

**Comment by SergeiShirkin** [comment]
@9dogs "при большом числе кубитов $N$ начальное значение угла $\theta$ будет стремиться к $0$"  - так, я думал сначала, что это у меня так написано, хотел исправить))) Число кубитов не N, а n. N - это общее число состояний. Общий смысл верен, но это справедливо при фиксированном K. А так из лекции понятно, что чем большее число состояний N (при этом, если K=1, например), тем меньше тета, и соответственно, больше нужно итераций.

**Comment by SergeiShirkin** [comment]
Я добавил уточнение к формулировке: https://github.com/SemyonSinchenko/qmlcourse/pull/278/commits/d57be7ae4ae0c49a76a88d4e8dc0a4ef5418f887
 Причинность не соблюдена (число итераций должно зависеть от угла тета, а на наоборот), но это в контексте доказательства формулы, а не объяснения алгоритма. Если получится правильнее это выразить, то было бы хорошо

**Comment by 9dogs** [comment]
@SergeiShirkin, да, $N$ - это число состояний, пардон.
>Чем меньше θ, тем больше нужно итераций. В тексте объясняется, как получена формула для оценки числа итераций, поэтому там говорится, что когда итераций много, угол θ близок к нулю

Ааа, понял! Речь о _требуемом_ числе итераций. Как вариант, можно "При большом общем количестве" заменить на "При большом требуемом количестве" в смысле "сколько требуется итераций для выполнения условий алгоритма". Но так тоже гораздо понятней, спасибо!

**Comment by SergeiShirkin** [comment]
@9dogs Спасибо, что заметил, а то действительно было неясно написано.
