### ISSUE TITLE
Добавить больше рассчетных примеров в лекцию про кубит

### ISSUE THREAD

**Issue by SemyonSinchenko** [SemyonSinchenko/qmlcourse#277]
Рядом с примерами на NumPy прямо матрички расписать еще для наглядности.

**Comment by flatslm** [comment]
Добрый день.

Могу взяться за этот issue. 
И вопрос - для измерений ("Еще пара слов об измерениях") так же нужны формулы?

Спасибо
Леонид

**Comment by SemyonSinchenko** [comment]
@flatslm Я тогда лучше объясню, откуда этот issue взялся. Был фидбек о том, что все очень сложно:

> У numpy расчета есть большой недостаток. Он что-то посчитал, кажется понятно что, а потом надо посчитать в первом задании скалярное произведение, я его считаю. А ответ не получается

> я сейчас перечитываю статью про кубиты. Все начинается просто и понятно, а потом фигак фигак Правило Борна. И приходит понимание, что чет я не умею считать ожидаемое значение оператора. Общая проблема вызвана наверное слабой математической подготовкой и быстрым усложнением.
Кажется, что если бы я в ручную посчитал побольше операций над векторами и матрицами, то лучше бы понял. Этим и занимаюсь по вечерам. Потом расскажу, помогло ли )

Отсюда и родилась идея о том, что помимо операций на NumPy надо рядом расписать все то же в виде матриц, явно показать как все получается и т.д. Именно примеры, прямо с цифрами. Наверное в измерения тоже надо, так как людям может быть трудно понять, как работает правило Борна, как считаются мат-ожидания результата измерения какого-то оператора в каком-то состоянии и т.д.

**Comment by SemyonSinchenko** [comment]
@flatslm Я добавил тебя в коллабораторы репозитория. Просто у нас ломается деплой стэйджинг версии и все проверки, если Pull-Request идет из форка. Поэтому просьба делать сразу внутри этого репозитория, просто создав ветку.
