### ISSUE TITLE
Опечатка в индексах

### ISSUE THREAD

**Issue by 9dogs** [SemyonSinchenko/qmlcourse#279]
[На этой строке](https://github.com/SemyonSinchenko/qmlcourse/blob/3f4a731965c6dc6dec877e0f6c1b9450b02e15ea/qmlcourseRU/book/qcalgo/simon_algorithm.md?plain=1#L40) сейчас под суммой по модулю два у первой и второй пары (x, z) одинаковые индексы 0.

Наверно, должно быть
```
$$
\langle x, z\rangle = \bigoplus_{i=0}^{2^n-1} x_i \wedge z_i = x_0 \wedge z_0 \oplus x_1 \wedge z_1 \oplus ... \oplus x_{2^n-1} \wedge z_{2^n-1}
$$
```

**Comment by vtrokhymenko** [comment]
@polyzer посмотришь?

**Comment by polyzer** [comment]
Да.
