### ISSUE TITLE
добавить `citation.cff`

### ISSUE THREAD

**Issue by vtrokhymenko** [SemyonSinchenko/qmlcourse#313]
[вот](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files) пример как использовать

в итоге, под «about» справа будет видно «cite this repository»

**Comment by SemyonSinchenko** [comment]
Может объединим это с #287 ?

**Comment by vtrokhymenko** [comment]
забыл о нем, обновил #287
