### ISSUE TITLE
Индексировать сайт курса в поиске Google

### ISSUE THREAD

**Issue by Yorko** [SemyonSinchenko/qmlcourse#320]
Админка SEO гугл: [webmaster.google.com](webmaster.google.com)

[Инструкция](https://support.google.com/webmasters/answer/6258314), tldr: нужен sitemap для GH pages [https://semyonsinchenko.github.io/qmlcourse/](https://semyonsinchenko.github.io/qmlcourse/), например, как у mlcourse.ai – [https://mlcourse.ai/sitemap.xml](https://mlcourse.ai/sitemap.xml)

**Comment by SemyonSinchenko** [comment]
Это должно помочь - https://github.com/executablebooks/jupyter-book/issues/880

**Comment by SemyonSinchenko** [comment]
- [ ] sitemap
- [ ] убрать из пути /_build/html/book/

**Comment by SemyonSinchenko** [comment]
sitemap: https://github.com/SemyonSinchenko/qmlcourse/pull/322

**Comment by SemyonSinchenko** [comment]
@vtrokhymenko Насколько "больно" будет на ods.ai поменять все ссылки на более короткие?

**Comment by vtrokhymenko** [comment]
> @vtrokhymenko Насколько "больно" будет на ods.ai поменять все ссылки на более короткие?
> Хочу изменить:
> `https://semyonsinchenko.github.io/qmlcourse/_build/html/book/index.html` -> `https://semyonsinchenko.github.io/qmlcourse/index.html`

не сильно, просто нужно будет пройтись по всем блокам и заменить. задача займёт где-то 30мин с тестированием
только нужно время правильно выбрать, дабы не было лага

**Comment by SemyonSinchenko** [comment]
Ок, тогда в отдельно ветке протестирую "укорачивание" ссылки.

**Comment by SemyonSinchenko** [comment]
Короткая ссылка: https://github.com/SemyonSinchenko/qmlcourse/pull/323

**Comment by SemyonSinchenko** [comment]
Появилось: https://github.com/SemyonSinchenko/qmlcourse/tree/gh-pages/docs
@vtrokhymenko Скажи, как будешь готов к переключению.

**Comment by vtrokhymenko** [comment]
точно не сейчас. где-то к 18 смогу, дабы зайти и всё одним махом

**Comment by SemyonSinchenko** [comment]
Есть две новости, хорошая и плохая:
- хорошая - ничего менять не надо, старые ссылки работают
- плохая - [новый вариант не рендерится](https://semyonsinchenko.github.io/qmlcourse)

**Comment by vtrokhymenko** [comment]
не нужно ли [тут](https://github.com/SemyonSinchenko/qmlcourse/blob/74cbf337b3da4562c8c8344330993360bb91f689/.github/workflows/deploy-book.yml#L93) писать `./qmlcourseRU/_build/html/book`?

**Comment by SemyonSinchenko** [comment]
Точно нет. Так как index.html, sitemap.xml и т.д. находятся как раз в `html`

**Comment by vtrokhymenko** [comment]
https://github.com/peaceiris/actions-gh-pages полностью прошел?

**Comment by SemyonSinchenko** [comment]
> https://github.com/peaceiris/actions-gh-pages полностью прошел?

Да

**Comment by vtrokhymenko** [comment]
чёт с путями не так
![image](https://user-images.githubusercontent.com/8581044/145212010-f8d5efe4-16e1-4a92-a80f-5d55806bff8a.png)

**Comment by SemyonSinchenko** [comment]
https://semyonsinchenko.github.io/qmlcourse
Работает?

**Comment by SemyonSinchenko** [comment]
Теперь индексация должна заработать правильно, потому что sitemap и index.html там, где поисковики могут их найти.

**Comment by vtrokhymenko** [comment]
> https://semyonsinchenko.github.io/qmlcourse
> Работает?

да, с `https://semyonsinchenko.github.io/qmlcourse` перенаправляет на `https://semyonsinchenko.github.io/qmlcourse/book/index.html`

**Comment by SemyonSinchenko** [comment]
Ссылки в ods.ai поменял

**Comment by SemyonSinchenko** [comment]
> > Ссылки в ods.ai поменял
> 
> так оно и так ведь работало + bullets забыл оставить

Не, не работало вроде

**Comment by vtrokhymenko** [comment]
@SemyonSinchenko можно закрывать это уже получается?
