### ISSUE TITLE
донастроить сборку pdf

### ISSUE THREAD

**Issue by vtrokhymenko** [SemyonSinchenko/qmlcourse#336]
ноги растут с #163 #198 

цель: автоматическая сборка всего курса

**Comment by SemyonSinchenko** [comment]
А чем текущий вариант плох?

**Comment by vtrokhymenko** [comment]
он разве автоматический? ну то есть когда обновляется master, то и pdf также?
и подскажи пж путь где этот файл лежит

**Comment by SemyonSinchenko** [comment]
Когда обновляется master, обновляется и .tex файл. Дальше каждый может собрать из него pdf, так как это однозначный и платформонезависимцй процесс.

**Comment by vtrokhymenko** [comment]
https://github.com/SemyonSinchenko/qmlcourse/blob/7bc27cf5542b9bbbd1b6833dfce298037973f472/README.md#build-the-book как-то прошло мимо меня, сейчас попробую

**Comment by SemyonSinchenko** [comment]
Вот дописать туда инструкции для других ОС (особенно винды) хорошо бы. Ну и потестить не только xelatex, но еще и lualatex и pdflatex.

**Comment by vtrokhymenko** [comment]
xelatex to\ и на mac нужно поставить, покуда эта программа не с коробки

**Comment by vtrokhymenko** [comment]
это нормально что такое имеется в ветке для сбора?

<img width="772" alt="example_debug" src="https://user-images.githubusercontent.com/8581044/146139788-463f9dd7-c3c1-4da8-a63e-632e17072b63.png">

**Comment by vtrokhymenko** [comment]
кажется что частично издеваемся с пользователей, дабы сами делали книгу. что мешает нам сами её уже в готовом pdf предоставить и сделать кнопку в репо для этого, как было ранее, удобнее ведь

это как купить macbook, но ос устанавливайте сами как хотите

**Comment by vtrokhymenko** [comment]
а как долго эта книга собиралась у тебя?

**Comment by SemyonSinchenko** [comment]
> а как долго эта книга собиралась у тебя?

Компиляция LaTeX это очень долго. Установка texlive на агент тоже очень долго (это один из самых больших мета-пакетов убунты, ядро меньше весит чем эта хрень, тк там шрифты).

> кажется что частично издеваемся с пользователей, дабы сами делали книгу

Обычно PDF нужен тем, кто уже знает, что такое LaTeX и умеет им пользоваться. Это люди из академической среды, которые привыкли читать "с бумаги" или "с pdf"

> что мешает нам сами её уже в готовом pdf 

Сейчас я и так ее периодически руками обновляю и относительно свежая версия лежит в ./pdf и любой ее может скачать.

**Comment by SemyonSinchenko** [comment]
Ставится он вроде без проблем на все системы: https://sourceforge.net/projects/xetex/

**Comment by vtrokhymenko** [comment]
долго это сколько? час, два, неделя?

даже если оставляем как есть, то нужно чтобы код выполнялся везде? а вот почему он показывает у тебя выдает ошибки в книге, нужно разобраться

**Comment by SemyonSinchenko** [comment]
> долго это сколько? час, два, неделя?

LaTeX так устроен, что собирать надо джважды. Один прогон минут 5 у меня на компе. Устанавливать TeX Live это еще пару минут.

**Comment by alexey-pronkin** [comment]
Ошибка вроде как правильная, там показывается как дебагать ошибки в jupyter, так и должно быть как я понимаю.


Тестировать разные движки точно не стоит, это пустая трата сил и займет тонну времени, потому что они фундаментально отличаются и придется держать три версии .tex под каждый движок.

**Comment by vtrokhymenko** [comment]
эти ошибки нужно решить, тк в лекциях на их основе показывают примеры/результаты, а видеть будут получается фигу наши студы

**Comment by SemyonSinchenko** [comment]
Потому что это не ошибки, а картинки @vtrokhymenko 
https://github.com/SemyonSinchenko/qmlcourse/blob/master/qmlcourseRU/_static/pythonblock/python_l11/example_debug.png

**Comment by SemyonSinchenko** [comment]
В сборке нет ошибок.
