### ISSUE TITLE
Исправить формулу для внешнего произведения(outer-product) в лекции Нотация дирака

### ISSUE THREAD

**Issue by CyberPunk2049** [SemyonSinchenko/qmlcourse#339]
В формуле внешнего произведения насколько я понимаю должен быть U - вектор-столбец, V- вектор-строка. Сейчас же наоборот.

**Comment by alexey-pronkin** [comment]
Да, правильно, спасибо за опечатку. Исправлю

**Comment by alexey-pronkin** [comment]
исправлено в #343, как будет мердж - закрою
