### ISSUE TITLE
CI/CD

### ISSUE THREAD

**Issue by SemyonSinchenko** [SemyonSinchenko/qmlcourse#44]
Добавить CI/CD в стиле https://jupyterbook.org/publish/gh-pages.html + Poetry + чтобы оно не падало из-за долгих рассчетов ноутбуков.

**Comment by SemyonSinchenko** [comment]
Сейчас базовый деплой сделан, теперь нужны фичи:
- пересбор всех UML
- пересбор только того, что реально обновилось

**Comment by dkorzhov** [comment]
Готов помочь по задачам CI/CD. Мне интересна любая практика в DevOps направлении. Пока много времени уделить не смогу, но готов разбираться в задачах и доводить их до конца.
Текущий мой стек Terraform+Jenkins+AWS, но разобраться в новом не проблема.

**Comment by SemyonSinchenko** [comment]
@dkorzhov Это был бы очень крутой вклад! Сейчас есть github action, который при пуше в мастер собирает Jupyter Book книгу с нуля и публикует ее. С этим есть проблема. При сборке JB он выполняет встроенный в книгу код, чтобы посчитать все аутпуты и графики. И это уже сейчас довольно долго, а каждая новая лекция будет докидывать по 2-5 минут сверху. Еще одна проблема в том, что нет возможности по кнопке собрать и задеплоить конкоетную ветку, чтобы упростить жизнь ревьюерам. Хочется иметь следующее:
- Пересборка и деплой только тех глав книги, в которых были изменения (JB позволяет пересобирать отдельные страницы или может использовать своей же кэш - тогда это будет автоматом)
- Тестовый билд для любого пулл реквеста (чтобы проверить, что PR не ломает сборку) и возможность по кнопке задеплоить результат

**Comment by dkorzhov** [comment]
Можно получить доступ к github action и гиту с книгой, чтобы потестировать текущий pipeline  и посмотреть, как можно улучшить? Если что, моя телега dkorzhov.
