### ISSUE TITLE
Разобраться с citations в  JB

### ISSUE THREAD

**Issue by SemyonSinchenko** [SemyonSinchenko/qmlcourse#49]
По ветке с квантовым SVM (открытый PR) видно, что библиография не работает. В логах он ругается на то, что нет такого ключа в bib файле, но ключ есть, инфа 100%. Сейчас все как в документации, надо понять почему не работает. Может там проблема в том, что нужно еще какой-то пакет в зависимости добавить, или что-то такое.

**Comment by SemyonSinchenko** [comment]
> Возможно глупое замечание: по документации, в одном из md-файлов должна быть директива ```{bibliography}```
> Может в этом проблема?

А кинь в меня ссылкой на документацию... Я что-то не пойму где это должно быть. В логах он сыпет warnings про то, что не нашел такогл ключа в библиографии, хотя выше в логах строка про то, что он успешно распарсил .bib файл

**Comment by karelin** [comment]
Дока тут: https://jupyterbook.org/content/citations.html
Пример маркдауна: https://github.com/executablebooks/jupyter-book/blob/master/docs/content/citations.md
там в самом конце

An example bibliography, for reference:

```{bibliography}
```

**Comment by SemyonSinchenko** [comment]
> Дока тут: https://jupyterbook.org/content/citations.html
> Пример маркдауна: https://github.com/executablebooks/jupyter-book/blob/master/docs/content/citations.md
> там в самом конце
> 
> An example bibliography, for reference:

Оно работает)))
Спасибо!
