### ISSUE TITLE
Общие пожелания/предложения/идеи

### ISSUE THREAD

**Issue by Yorko** [SemyonSinchenko/qmlcourse#56]
Поскольку не все общение будет в слэке ODS, удобно иметь такой ищью для обсуждения курса в целом, новых фич-реквестов и т.д.

**Comment by Yorko** [comment]
Есть идея для интро каждого блока сделать фоновую картинку. Иначе выглядит немного как сухая документация 

<img src="https://habrastorage.org/webt/iw/da/40/iwda40lrpkhpwxzb56tl8ptdmrs.png" />

**Comment by SemyonSinchenko** [comment]
У меня еще есть идея сделать общее интро курса, где рассказать больше о том, зачем учить QML, где он применим и тд.

**Comment by karelin** [comment]
Советую еще добавить в настройках кнопку github (как в доках на JB), раз репа открытая

**Comment by Yorko** [comment]
> У меня еще есть идея сделать общее интро курса, где рассказать больше о том, зачем учить QML, где он применим и тд.

Вот это надо первой статьёй – на Хабр. Заодно с анонсом курса, как регистрации подъедут.

**Comment by SemyonSinchenko** [comment]
Я еще что подумал. А что если заявить как "преимущество" нашего курса то, что он делается  сообществом и полностью open source? Типа каждая лекция ревьюится разными людьми, чтобы она была одновременно корректной и понятной и тд. Это в раздел "Почему именно наш курс". @Yorko что думаешь? Просто вот есть курс на eDx, но там был ровно один автор и это чисто как он видит. Есть Qiskit textbook, но опять же это то, как видит ситуацию IBM. А у нас типа коммьюнити и демократия. Или это такое себе преимущество?

**Comment by karelin** [comment]
> Я еще что подумал. А что если заявить как "преимущество" нашего курса то, что он делается сообществом и полностью open source?

Не уверен. Большинство нормальных книг по квантовой физике - это авторская история, обычно одного-двух человек. Скорее это экспериментальная история, посмотрим, как ее примут.

**Comment by vtrokhymenko** [comment]
предлагаю эту тему вести в дискуссиях, вот [тут](https://github.com/SemyonSinchenko/qmlcourse/discussions/82), где есть что-то на подобии даже thread-ов
будет здорово, если вы свои заметки перенесете туда
