### ISSUE TITLE
Лекция про "стандартные" квантовые алгоритмы

### ISSUE THREAD

**Issue by SemyonSinchenko** [SemyonSinchenko/qmlcourse#6]
Время до сентября, можно добавить больше материала. Идея - рассказать про "классические" квантовые алгоритмы. Что-то простое, может задачу Дойча как вариант? Ну либо даже QFT + Shor?

**Comment by Carinetta** [comment]
День добрый. Если ещё актуально, могу взять на себя Саймона, Гровера, телепортацию

**Comment by SemyonSinchenko** [comment]
@doktrster ^^^ Обсудите тогда? Можно разделить задачи, например отдельно сделать Дойча и что-то еще простое, а отдельно Гровера и тд. @Carinetta А случайно не сможешь рассказать Гровера для задачи глобальной оптимизации? Нам это пригодилось бы в лекции про гибридный SVM

**Comment by Carinetta** [comment]
Да, я напишу Сергею.
Про Гровера и ххл давайте я подумаю, что и как смогу из себя выжать (чтоб всем понятно было и мне).
Просто в машинке я не шарю почти нисколько, про опорняк и ядра буквально что-то читала много лет назад. С точки зрения мл вряд ли я сумею хорошо объяснить - если только в коллабе (заодно обсудим).

По химии и графам на NumPy что-то могу порассказывать (эволюция унитарная/неунитарная, тёмные состояния) - если это нужно. И главное ещё успеть подготовиться.

**Comment by SemyonSinchenko** [comment]
HHL был бы мега крутым вкладом, там (на мой взгляд) не надо особо знать машинку, а скорее надо реально хорошо шарить в обычных квантовых алгоритмах. И самое сложное объяснить его так, чтобы было понятно, потому что матанчик там на мой взгляд оч жесткий... В любом случае спасибо!

**Comment by Carinetta** [comment]
Пока не за что)
Попробую накидать на бумажке план рассказа со всеми схемами и разошлю на почту, наверное.
Сколько времени у меня есть на альфа-версию? Гровер и HHL?
Остальное пока не нужно ведь?

**Comment by SemyonSinchenko** [comment]
Можно даже просто HHL - как я себе это представляю, там материала хватит на две лекции минимум - у нас все же часть целевой аудитории это практики (программисты, дата сайнтисты и тд). Гровера @doktrster брал, вомзожно у него уже есть наработки. Мы тут все не очень в мэйл-листы, у нас больше обсуждение в slack (у нас канал в слаке Open Data Science https://ods.ai/). Но если удобнее через почту, то я думаю тоже сойдет. Времени много - мы надеемся подготовить большую часть материалов к 1-му сентября. За месяц успеешь сделать план рассказа? Ну там к августу, чтобы успеть все оформить.

**Comment by Carinetta** [comment]
Ок, подала заявку в ods.ai/
Да, буду оч стараться подготовиться к августу железно.
Если вдруг мало ли что не получится - сообщу заранее.

**Comment by doktrster** [comment]
Что-то я выпал из процесса, не следил за почтой последние пару дней, поздно прочитал ваши сообщения. Гровера уже делаю, в ближайшие пару недель буду выкладывать (после Дойча/Дойча-Йожи), а потом попробую переключиться на алгоритм Шора, и еще хотел помочь с матрицами плотности и, возможно, с квантовой коррекцией ошибок. @Carinetta, спасибо за предложенные темы! Алгоритм Саймона, телепортация, HHL - все эти темы свободны. Тёмные состояния - вот это интересно, если @SemyonSinchenko не против, то было бы супер, если бы вы это сделали

**Comment by Carinetta** [comment]
Утро доброе)
Давайте тогда начну с простого - раскидаю Саймона и телепортацию. Потом попробую взяться за HHL: дело в том, что ввиду отсутствия сходимости в литературе, скорее всего мне придётся самой выводить матричные описания - надеюсь, получится.
Тёмными, к сожалению, не смогу в должной мере поделиться: только вчера мой преподаватель строго-настрого запретил разглашать вычисления (тема сырая, все разработки закрытые). Прикольнее было бы показать, как  моделировать тёмные состояния на питоне, но низя...
Можно упомянуть в общем рассказе об эволюции, гамильтониане, рабиевских осцилляциях, например, - подумаю, что и сколько из этого может быть в тему.

**Comment by karelin** [comment]
> Тёмными, к сожалению, не смогу в должной мере поделиться: только вчера мой преподаватель строго-настрого запретил разглашать вычисления (тема сырая, все разработки закрытые). Прикольнее было бы показать, как моделировать тёмные состояния на питоне, но низя...

Может можно что-то написать на основе уже опубликованных статей (даже других групп)?

**Comment by Carinetta** [comment]
Вот хочу поискать, что в свободном лежит.
Сообщу по итогу.

**Comment by SemyonSinchenko** [comment]
@Carinetta Звучит круто! Тогда как тебя добавят в ods.ai напиши там мне в лс (там @sem) - я добавлю тебя в закрытый канал с обсуждением этого курса.

**Comment by vtrokhymenko** [comment]
подтвердил заявку на вступление в ods еще 3 дня назад

**Comment by SemyonSinchenko** [comment]
@SergeiShirkin Как я понимаю, именно этот issue можно закрывать, да? Ты ведь свою часть полностью сделал, а для HHL есть отдельная задача.

**Comment by SergeiShirkin** [comment]
@SemyonSinchenko Пока не закрывай, я на выходных начну присылать текст по алгоритму Гровера
